### PR TITLE
Implement machine-exec support

### PR DESCRIPTION
**Pull request by vzhukovs**
#### Preface
The following changes proposal provides implementation for complete Machine Exec support.
Support for Machine Exec will allow user to run Devfile command in component which is bound to particular command. Also display the state of listening endpoints and create port forwarding for Devfile endpoints.

editor

#### Test changes
To test changes there workspace from the following factory links should be created:

- [vaading-demo](https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/#https://github.com/vzhukovs/vaadin-demo?che-editor=https://gist.githubusercontent.com/vzhukovs/95337765cbde9b6ed1f252e6e77671a2/raw/ce2508d6cd101d400a4b99cc788933ef5f7eff84/che-editor.yaml)

<details><summary>vaading-demo (devfile.yaml)</summary>
<p>

```yaml
schemaVersion: 2.1.0
metadata:
  name: vaadin-demo
components:
  - name: postgres
    container:
      image: postgres:14.3-alpine
      memoryLimit: 300Mi
      endpoints:
        - exposure: none
          name: db
          protocol: tcp
          targetPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - name: postgres-data
          path: /var/lib/postgresql/data
  - name: dev
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-9436df2
      memoryLimit: 3Gi
      endpoints:
        - exposure: none
          name: debug
          protocol: tcp
          targetPort: 5005
        - exposure: public
          name: 8080-tcp
          protocol: http
          targetPort: 8080
      volumeMounts:
        - name: m2
          path: /home/user/.m2
  - name: postgres-data
    volume:
      size: 256Mi
  - name: m2
    volume:
      size: 1G
commands:
  - id: spring-boot-run
    exec:
      label: Spring Boot run
      component: dev
      commandLine: >-
        ./mvnw
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: run
  - id: maven-build
    exec:
      label: Maven Build
      component: dev
      commandLine: >-
        ./mvnw clean install
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: build
  - id: spring-boot-debug
    exec:
      label: Spring Boot run with debug
      component: dev
      commandLine: >-
        java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 target/*.jar
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: debug
```

</p>
</details>

Or any other sample, using the factory link:

`https://che-host/#https://repository/?che-editor=https://gist.githubusercontent.com/vzhukovs/95337765cbde9b6ed1f252e6e77671a2/raw/ce2508d6cd101d400a4b99cc788933ef5f7eff84/che-editor.yaml`

---

#### Commands Panel

commandPanel

Toolbar contains the following actions:

- **Sort by Name**
  <sub>Sorts commands by name alphabetically</sub>

- **Sort by Type**
  <sub>Sorts commands by type (New Terminal and others)</sub>

- **Show Run Commands**
  <sub>Shows commands which have `group.kind: run` type</sub>

- **Show Build Commands**
  <sub>Shows commands which have `group.kind: build` type</sub>

- **Show Test Commands**
  <sub>Shows commands which have `group.kind: test` type</sub>

- **Show Debug Commands**
  <sub>Shows commands which have `group.kind: run` type</sub>

- **Show Deploy Commands**
  <sub>Shows commands which have `group.kind: deploy` type</sub>

- **Show Components**
  <sub>Switches to display mode between showing workspace components or not</sub>

- **Execute Devfile Command**
  <sub>Executes Run Anything command to prompt user to select Devfile command to run</sub>

- **Execute Selected Command**
  <sub>Executes selected command in the tree</sub>

- **Expand All**
  <sub>Expands command tree</sub>

- **Collapse All**
  <sub>Collapses command tree</sub>

Tree contains the following nodes based on the display options selected by the **Show Components** action:

- **Workspace**
  <sub>Current workspace</sub>

- **\<Component name>**
  <sub>Component name if it provides any command. If component doesn't provide any command, it will not be displayed at all</sub>

- **New Terminal [\<Component name>]**
  <sub>Action to open terminal in selected **\<Component name>**</sub>

- **\<Command label> [\<Command name>]**
  <sub>Action to run the following command</sub>

or simple list of the **\<Command label> [\<Command name>]** among with **New Terminal [\<Component name>]** as it shown below:

commandsList

Executing **Execute Devfile Command** will open Run Anything popup menu with the all commands that was provided by Devfile:

runAnythingMenu

Executing **Execute Selected Command** will create and run a temporary Run Configuration with the following configuration provided by the **\<Command label> [\<Command name>]**, such as component name, current working directory, command line, etc.:

runConfiguration

Executing **New Terminal [\<Component name>]** will open the terminal in \<Component name>.

Also it is possible to create own Devfile command, which will be saved in workspace (IntelliJ IDEA) settings and not synced with Original/Flattened Devfile(at this moment):

customRunConfiguration

---

#### Endpoints Panel

endpointsPanel

Toolbar contains the following actions:

- **Sort by Name**
  <sub>Sorts endpoints by name alphabetically</sub>

- **Hide Plugins Endpoints**
  <sub>Hides endpoints which were provided by plugin components</sub>

- **Expand All**
  <sub>Expands endpoint tree</sub>

- **Collapse All**
  <sub>Collapses endpoint tree</sub>

- **Open in Browser**
  <sub>Opens selected endpoint in browser tab if endpoint provides an URL to preview</sub>

- **Copy Endpoint URL to Clipboard**
  <sub>Copies the endpoint URL if endpoint provides an URL to preview</sub>

Green status marker displays the running state of endpoint which also allows to open the URL to browse the service which is bound on the following port:

endpointHover

When user starts the service on port which is not processed by the Endpoints panel, the following notifications prompted to the user to perform the port forward to particular service port:

notificationsPanel

fixes https://github.com/eclipse/che/issues/21212
fixes https://github.com/eclipse/che/issues/21139
fixes https://github.com/eclipse/che/issues/21141
fixes https://github.com/eclipse/che/issues/21140

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
I'm not sure it makes sense to have the buttons for filtering the commands list by kind.
Some of my concerns:
1. Only commands with Run and Build kind are visible by default. Why we should hide other commands?
2. What may be the reason for the user to hide some commands by filtering them? Considering typical Devfile contains just a few commands to work with the project.

**Comment by azatsarynnyy** [comment]
Are there some benefits that the `Execute Devfile Command` feature brings to the user? Compared to just clicking on the required command in the list.
To me, `Execute Devfile Command` does the same, but requires more steps.

**Review by azatsarynnyy — APPROVED** [review]
I've tested it with java-spring-petclinic sample. Everything works great.

**Comment by vzhukovs** [comment]
> Are there some benefits that the `Execute Devfile Command` feature brings to the user? Compared to just clicking on the required command in the list.
> To me, `Execute Devfile Command` does the same, but requires more steps.

Yep, event if Commands panel is hidden on the UI, it is possible to double tap Control key and Run Anything popup will be shown.

**Comment by vzhukovs** [comment]
>Only commands with Run and Build kind are visible by default. Why we should hide other commands?

Typically ,they are the commonly used commands from the Devfile and the idea to focus user only on these commands from the start.

>What may be the reason for the user to hide some commands by filtering them? Considering typical Devfile contains just a few commands to work with the project.

For example, complex Devfile might contain commands with kind `Test`, so there is no reason to show them at workspace start.

**Review by azatsarynnyy — APPROVED** [review]

**Pull request merged**
